name: haul-app-test
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: haul-app
    ports:
      # not to mess with your local mongo, if any spinning
      - "27018:27017"
    volumes:
      - ./.data/db:/data/db
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
  mongo-express: # to access data easily
    image: mongo-express
    restart: always
    ports:
      - 8181:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: haul-app
      ME_CONFIG_MONGODB_URL: mongodb://root:haul-app@mongo:27017/
